// Base URLs to access APIs
const restCountriesBaseUrl = "https://restcountries.eu/rest/v2"

// API endpoints
export const getCountryNames = restCountriesBaseUrl + "/all?fields=name"

// Activity types
export const getActivityTypes = [
    "Aeroplane flying and aerobatics experiences",
    "Air Sphering",
    "Astronomy",
    "BASE Jumping",
    "Bungee Jumping",
    "Falconry experience days",
    "Gliding lessons",
    "Gyrocopter flying",
    "Hang Gliding experience",
    "Helicopter Flights",
    "Hot Air Balloon Rides",
    "Indoor Skydiving",
    "Kites and Power Kites",
    "Microlights",
    "Model airplanes, helicopters and multirotors (drones)",
    "Model Rockets",
    "Paragliding and Paramotoring",
    "Parascending",
    "SCAD – Suspended Catch Air Device",
    "Skydiving",
    "Wing Walking",
    "4×4 driving experience",
    "Activity Holidays for families and teenagers",
    "Adventure Races",
    "Air rifle and air pistol shooting",
    "Airsoft",
    "American Football",
    "Animal Parks, Wildlife Parks and Zoos",
    "Archery",
    "Assault courses and Obstacle course races",
    "Athletics",
    "Backyard Sleepovers",
    "Badminton",
    "Baseball and Softball",
    "Basketball",
    "Baton Twirling",
    "Battle Reenactments",
    "Beach Activities",
    "Beachcombing",
    "Bicycle Polo",
    "Bird watching holidays",
    "BMX biking",
    "Boccia",
    "Bootcamps for fitness",
    "Bouldering",
    "Bowls",
    "Brushboarding",
    "Bubble Football",
    "Bushcraft and survival courses",
    "Camel trekking holidays",
    "Camogie",
    "Camping",
    "Canyoning and Canyoneering",
    "Capoeira",
    "Carnivals",
    "Carriage driving",
    "Cave biking underground",
    "Caving and potholing",
    "Cheerleading",
    "Chinese Martial Arts",
    "Circus Skills",
    "Clay Pigeon Shooting",
    "Climbing courses and climbing holidays",
    "Concerts, Festivals and Gigs",
    "Conkers",
    "Cookout",
    "Crazy Golf and Mini Golf, Pitch and Putt",
    "Cricket",
    "Croquet",
    "Cycling fitness training",
    "Dance, Street Dance",
    "Den Building and Bivouacs",
    "Digger and JCB driving",
    "Dodgeball",
    "Dog Scootering",
    "Drag Racing",
    "Driving Experience Days",
    "Duathlon",
    "Eclipse Sphering and Eclipse Zorbing",
    "Equestrian (horse Riding, eventing, racing, dressage, cross country)",
    "Exercise and fitness",
    "Exploring holidays",
    "Fencing",
    "Fives (rugby)",
    "Floorball",
    "Folk Dancing",
    "Footbags",
    "Football and Soccer",
    "Free Running and Parkour",
    "Fruit Picking",
    "Fun fairs",
    "Futsal",
    "Gaelic Football",
    "Gap Year Travelling",
    "Gardening",
    "Geocaching",
    "Gladiator Training",
    "Goalball",
    "Go Ape forest high wire adventures ropes courses",
    "Go Karting",
    "Golf Holidays",
    "Grass skiing",
    "Grass sledging",
    "Grass karting",
    "Greyhound Racing",
    "Grow Your Own Vegetables",
    "Grouse Shooting",
    "Gymnastics",
    "Handball",
    "Harness Racing",
    "Hiking holidays",
    "Hockey",
    "Horse Boarding",
    "Horse Racing",
    "Horse Riding",
    "Hurling",
    "Jogging and running",
    "Jousting",
    "Kite Boarding",
    "Kite Buggying",
    "Korfball",
    "Lacrosse",
    "Landboarding",
    "Land Sailing and Land Yachting",
    "Landscape painting holidays and art holidays",
    "Laser Clay Shooting",
    "Laser Tag",
    "Lawn Mower Racing",
    "Live Action Role Playing Games",
    "Llama trekking",
    "Marathon Running",
    "Minimoto",
    "Modern Pentathlon",
    "Monster Truck Driving Experience",
    "Motorcycling, Motocross and dirt biking",
    "Motor Sports",
    "Mountain Bikes",
    "Mountain Boarding",
    "Mountaineering",
    "Mud Racing",
    "Multi Use Games Areas and playgrounds for adults",
    "Nascar",
    "Yoga",
    "Zorbing"
];

// Fitness levels
export const fitnessLevels = [{value: -1, desc: "No fitness level"},
    {value: 0, desc: "Unfit, no regular exercise, being active is very rare"},
    {value: 1, desc: "Not overly fit, occasional recreational fitness activity, active a few times a month"},
    {value: 2, desc: "Moderately fit, enjoys fitness activities for recreation, active once or twice a week"},
    {value: 3, desc: "Fit, may compete occasionally in small scale events, active most days"},
    {value: 4, desc: "Very fit, competitive athlete, extremely active"}]
