#!/usr/bin/env bash
nohup java -jar ../server-dev/libs/server-0.0.1-SNAPSHOT.jar --server.port=9499 & # /tmp 2>> /dev/null >>/dev/null & # convert to be run with service
nohup serve -s ../client-dev/dist -l 9500 & # /tmp 2>> /dev/null >>/dev/null & # convert to be run with service